### ISSUE TITLE
how to have a better score 

### ISSUE THREAD

**Issue by EnokiEnoki** [aws-samples/sound-anomaly-detection-for-manufacturing#1]
Hey, 
I tried your repo and it is perfect for what I need to do, but the problem is that I can't seem to improuve it so that there is no more abnormal normal and no more normal abnormal. 
can you help me improuve it ? of maybe some guidance please ? thank you !

**Comment by EnokiEnoki** [comment]
@michaelhoarau

**Comment by michaelhoarau** [comment]
Hi,
What your are asking is not possible. There will always be false positives and false negatives. In many cases, a classification algorithm cannot be perfect as there will also be observations that cannot be distinguished (event by a human for that matter). The only thing you can do, is to integrate a machine learning results into a human-in-the-loop process. There, you can use confidence level of a given results: when the confidence level is lower than a threshold that you decide depending on the criticality of your business, you send it to someone to check it. Instead of checking 100% of the results, you manually check the few % that the ML system cannot decide on.

**Comment by EnokiEnoki** [comment]
hi I understand, do you know how I can improuve it please ? right now I at 64 abnormal normal and 69 normal abnormal.

**Comment by michaelhoarau** [comment]
As I mentioned, you can't improve the results by just improving the "algorithm". You need to change the approach, or collect more data. If you don't collect more data, it's not possible to improve the outcome. You have to compromise between recall and precision in this specific case. I recommend you read about machine learning metrics, identify which one is best for your business case and focus on this one. I also you recommend you research human-in-the-loop approach as I mentioned in my previous message.

**Comment by EnokiEnoki** [comment]
I see, I will be trying to implement a human in the loop 
thank you very much
